services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.http-server
    command: pnpm --filter @repo/db exec prisma migrate deploy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

  http-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.http-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  ws-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws-server
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${POSTGRES_DB}
    depends_on:
      - http-server

volumes:
  pgdata: