# Use Node base
FROM node:22-alpine

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

# Copy only necessary files first (better caching)
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml package.json turbo.json ./
COPY packages ./packages
COPY apps/web ./apps/web

# Install dependencies
RUN pnpm install

# Generate prisma client
RUN pnpm turbo run db:generate

# Build only http-server (if using turbo)
RUN pnpm turbo build --filter=web

# Expose port
EXPOSE 3001

# Run the app
CMD ["pnpm", "--filter", "web", "start"]